name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        target_cpu:
        - haswell
        - skylake
        - znver2
        - znver3
    steps:
    - name: Checkout x265
      uses: actions/checkout@v2
      with:
        path: x265
        fetch-depth: 0
    - name: Cache mimalloc
      id: cache-mi
      uses: actions/cache@v2
      with:
        path: mimalloc
        key: ${{matrix.target_cpu}}-${{matrix.toolchain}}-mi
    - name: Checkout mimalloc
      uses: actions/checkout@v2
      with:
        path: mimalloc
        repository: microsoft/mimalloc
        ref: v2.0.2
      if: steps.cache-mi.outputs.cache-hit != 'true'
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        update: true
        install: >-
          base-devel
          mingw-w64-clang-x86_64-nasm
          mingw-w64-clang-x86_64-toolchain
          mingw-w64-clang-x86_64-cmake
          mingw-w64-clang-x86_64-ninja
    - name: Compile mimalloc
      run: |
        mkdir build
        cd build
        cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=/usr/local
        ninja
      working-directory: mimalloc
      if: steps.cache-mi.outputs.cache-hit != 'true'
    - name: Install mimalloc
      run: ninja install
      working-directory: mimalloc/build
    - name: Setup build dir
      run: mkdir -p build/10b
    - name: Download profdata
      run: iwr https://github.com/AmusementClub/blobs/raw/profdata/x265.profdata -OutFile x265.profdata
      shell: pwsh
    - name: Compile x265 10bit
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        cmake -GNinja ../../x265/source -DENABLE_AVISYNTH=OFF -DENABLE_VPYSYNTH=OFF -DHIGH_BIT_DEPTH=ON -DENABLE_HDR10_PLUS=ON -DENABLE_SHARED=OFF -DENABLE_CLI=ON -DENABLE_PIC=ON -DSTATIC_LINK_CRT=ON  -DTARGET_CPU=${{matrix.target_cpu}} -DUSE_MIMALLOC=ON -DUSE_LTO=ON -DCMAKE_EXE_LINKER_FLAGS=-LD:/a/_temp/msys/msys64/usr/local/lib -DCMAKE_ASM_NASM_FLAGS=-w-macro-params-legacy -DCMAKE_CXX_FLAGS="-fprofile-instr-use=${{github.workspace}}/x265.profdata"
        ninja
        strip -s x265.exe
      working-directory: build/10b
    - name: Package
      run: |
        mkdir dist
        cp /clang64/bin/libc++.dll /clang64/bin/libunwind.dll dist
        cp build/10b/x265.exe dist
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: x265-win64-${{matrix.target_cpu}}-${{matrix.toolchain}}
        path: dist/*
